# Generated by Django 6.0.4 on 2026-06-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registros', '0006_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Enhancement', 'Part'), ('Explosive', 'Explosive'), ('Misc', 'Misc')], max_length=100, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
            ],
        ),
        migrations.CreateModel(
            name='EngRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_quantity', models.IntegerField(default=1)),
                ('eng_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='Engineering.engitem')),
            ],
        ),
        migrations.CreateModel(
            name='EngReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='Engineering.engrecipe')),
            ],
        ),
    ]
