# Generated by Django 6.0.4 on 2026-05-31 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registros', '0006_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelcraftingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_chance', models.FloatField()),
                ('vendor_price', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
            ],
        ),
        migrations.CreateModel(
            name='GemCuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Orange', 'Orange'), ('Purple', 'Purple')], max_length=50)),
                ('gem_cut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jewelcrafting.jewelcraftingitems')),
            ],
        ),
    ]
