# Generated by Django 6.0.4 on 2026-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewelcrafting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelcraftingitems',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Epic', 'Epic')], default='Rare', max_length=50),
        ),
    ]
