# Generated by Django 6.0.4 on 2026-05-20 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registros', '0006_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlchemyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Flasks', 'Flasks'), ('Elixirs', 'Elixirs'), ('Potions', 'Potions')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlchemyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_quantity', models.IntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Alchemy.alchemygroup')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.item', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('alchemy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_for', to='Alchemy.alchemyitem')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_as_reagent_in', to='Registros.item')),
            ],
            options={
                'unique_together': {('alchemy_item', 'reagent')},
            },
        ),
    ]
