# Generated by Django 6.0.4 on 2026-05-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alchemy', '0001_initial'),
        ('Registros', '0006_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alchemyitem',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alchemy_item', to='Registros.item'),
        ),
    ]
