# Generated by Django 6.0.4 on 2026-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alchemy', '0002_alter_alchemyitem_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alchemygroup',
            name='search_group',
            field=models.CharField(choices=[('Flask', 'Flasks'), ('Elixir', 'Elixirs'), ('Potion', 'Potions')], default='Flask', max_length=50),
        ),
    ]
