# Generated by Django 6.0.4 on 2026-05-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alchemy', '0003_alchemygroup_search_group'),
        ('Registros', '0006_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_output', to='Registros.item')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='itemreagent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alchemyitem',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alchemy.recipe'),
        ),
        migrations.AddField(
            model_name='itemreagent',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='Alchemy.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='itemreagent',
            unique_together={('recipe', 'reagent')},
        ),
        migrations.RemoveField(
            model_name='itemreagent',
            name='alchemy_item',
        ),
    ]
