### Variables
@baseUrl = http://localhost:8000/api
@authToken = your_jwt_token_here


###
GET {{baseUrl}}/jewelcrafting/items/?faction=Alliance&realm=Nightslayer&selected_record=8629
Content-Type: application/json

