# Generated by Django 6.0.4 on 2026-06-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registros', '0006_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Agility', 'Agility'), ('Spell power', 'Spellpower'), ('Stamina', 'Stamina'), ('Strength', 'Strength'), ('Healing', 'Healing'), ('Hit Rating', 'Hit'), ('Pet Buff', 'Pet'), ('Other', 'Other')], max_length=100, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
            ],
        ),
        migrations.CreateModel(
            name='CookingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_quantity', models.IntegerField(default=1)),
                ('cook_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='Cooking.cookingitem')),
            ],
        ),
        migrations.CreateModel(
            name='CookingReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='Cooking.cookingrecipe')),
            ],
        ),
    ]
