# Generated by Django 6.0.4 on 2026-06-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registros', '0006_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Enhancement', 'Enhancement'), ('Consumable', 'Consumable'), ('Gear', 'Gear'), ('Misc', 'Misc')], max_length=100, null=True)),
                ('profession', models.CharField(blank=True, choices=[('Blacksmithing', 'Blacksmithing'), ('Engineering', 'Engineering'), ('Leatherworking', 'Leatherworking'), ('Tailoring', 'Tailoring')], max_length=100, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
            ],
        ),
        migrations.CreateModel(
            name='BoeRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_quantity', models.IntegerField(default=1)),
                ('boe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='Boe.boeitem')),
            ],
        ),
        migrations.CreateModel(
            name='BoeReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='Boe.boerecipe')),
            ],
        ),
    ]
