# Generated by Django 6.0.4 on 2026-05-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSubclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='Registros.itemclass')),
            ],
            options={
                'unique_together': {('name', 'item_class')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingame', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('quality', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], default='Common', max_length=20)),
                ('vendor_sell_price', models.IntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='iconos')),
                ('item_subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.itemsubclass')),
            ],
        ),
    ]
