# Generated by Django 6.0.4 on 2026-05-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_sell_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
            ],
            options={
                'unique_together': {('item', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PricingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_value', models.IntegerField(default=0)),
                ('min_buyout', models.IntegerField(default=0)),
                ('num_auctions', models.IntegerField(default=0)),
                ('historical', models.IntegerField(default=0)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.records')),
            ],
        ),
    ]
