# Generated by Django 6.0.4 on 2026-05-03 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_alter_item_icon_alter_item_vendor_sell_price_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.IntegerField(unique=True)),
                ('realm_name', models.CharField(max_length=50)),
                ('faction', models.CharField(choices=[('Horde', 'Horde'), ('Alliance', 'Alliance')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='auction_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registros.auctionhouse'),
        ),
    ]
