# Generated by Django 6.0.4 on 2026-05-05 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0003_auctionhouse_records_auction_house'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='records',
            unique_together={('auction_house', 'timestamp')},
        ),
        migrations.CreateModel(
            name='ItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_value', models.IntegerField(default=0)),
                ('min_buyout', models.IntegerField(default=0)),
                ('num_auctions', models.IntegerField(default=0)),
                ('historical', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.item')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_records', to='Registros.records')),
            ],
            options={
                'unique_together': {('item', 'record')},
            },
        ),
        migrations.DeleteModel(
            name='PricingData',
        ),
        migrations.RemoveField(
            model_name='records',
            name='item',
        ),
    ]
