# Generated by Django 6.0.4 on 2026-05-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0004_alter_records_unique_together_itemrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecord',
            name='overriden_min_buyout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
