# Generated by Django 6.0.4 on 2026-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0005_itemrecord_overriden_min_buyout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dynamic_data', models.JSONField()),
            ],
        ),
    ]
